### ISSUE TITLE
Quickstart - s3 access error

### ISSUE THREAD

**Issue by richardbatstone** [allenai/pawls#114]
I tried to download the pre-processed papers from the s3 bucket but got an access error. When I run the aws s3 sync command I get this error:

> fatal error: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied

If I open [https://s3.console.aws.amazon.com/s3/buckets/ai2-s2-pawls-public/example-data](https://s3.console.aws.amazon.com/s3/buckets/ai2-s2-pawls-public/example-data) in a browser I get this error:

> You don’t have permission to get object details
> After you or your AWS administrator have updated your permissions to allow the s3:ListBucket action, refresh the page. Learn more about Identity and access management in Amazon S3
> API response
> Access Denied

I have a free-tier AWS account but haven't used it before (only GCP) so perhaps I need to do additinal configuration? However, I am able to access other public S3 buckets.

Any thoughts much appreciated (and thanks for what looks like a really impressive project)!

**Comment by victor-ab** [comment]
I guess that's for AllenAI internal use only.

**Comment by DeNeutoy** [comment]
@richardbatstone, @victor-ab - sorry about this! It absolutely should be open access, let me try to correct that, i'll let you know once it's done.

**Comment by DeNeutoy** [comment]
Ok, sorry about that - the files are now public, I accidentally didn't change their permissions when I uploaded them to the bucket. Sorry for the delay in answering this!

**Comment by julianmack** [comment]
Hi @DeNeutoy- I'm still getting authentication errors as of just now I'm afraid.

If I go to: https://s3.console.aws.amazon.com/s3/buckets/ai2-s2-pawls-public/example-data
I see the following:
![image](https://user-images.githubusercontent.com/32888280/106947838-d2e98380-6722-11eb-9aad-493abbb39b38.png)


This feels like it is similar to the error that I'm getting on the command line. When I run:
```
aws s3 sync s3://ai2-s2-pawls-public/example-data ./skiff_files/apps/pawls/papers/
```
it outputs
```
fatal error: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied
```

**Comment by DeNeutoy** [comment]
*throws computer at wall*

Sorry @julianmack , you need to add in `--no-sign-request` to the command, and I also needed to edit the bucket policy. Can you try this:

`aws s3 sync s3://ai2-s2-pawls-public/example-data ./skiff_files/apps/pawls/papers/ --no-sign-request`? I checked it worked on a server where I didn't have my work access keys, so I think this is correct.

**Comment by julianmack** [comment]
Hi @DeNeutoy - great - this worked perfectly! Many thanks for your time :+1:

**Comment by richardbatstone** [comment]
Great, many thanks @DeNeutoy - that worked for me too.
