### ISSUE TITLE
relations - example/documentation

### ISSUE THREAD

**Issue by julianmack** [allenai/pawls#119]
Would it be possible to see an example of a valid `relations` configuration. i.e. 

```
{
    "output_directory": "/skiff_files/apps/pawls/papers/",
    "labels": [...],
    "relations": [<what should this be?>],
    "users_file": "/users/allowed.txt"
}

```
I have tried a few different things but I don't seem able to export the relations. Many thanks in advance

**Comment by lolipopshock** [comment]
Thanks for pointing out this issue! To clarify:
1. you just need to put some relation names there:
    ```
    "relations":[
        "relation-name-1",
        "relation-name-2",
        ....
    ]
    ```
2. currently PAWLS does not support exporting "relations" - will add that very soon. 
3. and will also add the documentation/tutorial for doing that as well. 

Please let us know if you have other questions!

**Comment by julianmack** [comment]
Hi @lolipopshock - many thanks (I just saw this). Much appreciated. Thanks for getting back so quickly - this is a really great tool

**Comment by lolipopshock** [comment]
@julianmack  Thanks! Ahh I just made a mistake in specifying the relations - 

> Hi @lolipopshock - many thanks (I just saw this). Much appreciated. Thanks for getting back so quickly - this is a really great tool

Thanks! Just updated the specification for relations above - I shared an incorrect example earlier.

**Comment by enzorc** [comment]
Hello!

Do we know when the export of relations will be available ?

Thanks!
