### ISSUE TITLE
Update UI Dependencies

### ISSUE THREAD

**Issue by codeviking** [allenai/pawls#157]
There's a lot of security alerts related to the UI application's dependencies, which can be seen here:
https://github.com/allenai/pawls/security/dependabot

We should update the dependencies noted there to resolve the associated security alerts.

**Comment by codeviking** [comment]
I'm going to ping Doug Downey and Shannon about this.

**Comment by lolipopshock** [comment]
Hey @codeviking ! Sorry it seems I don't have access to this link -- https://github.com/allenai/pawls/security/dependabot .. Maybe it requires my role on this GitHub project to be somewhat changed/reconfigured? Thanks!

**Comment by codeviking** [comment]
@lolipopshock Oops. Sorry about that. I just made you an owner of the repository. I also gave all of the S2 Research team write.

Let me know if you still don't have access!

**Comment by lolipopshock** [comment]
Yeah can see it now! Thanks!
