### ISSUE TITLE
Where are annotations stored?

### ISSUE THREAD

**Issue by maiiabocharova** [allenai/pawls#177]
Hello, sorry for stupid question, but when I launch pawls using docker - after annotating files where the annotations are stored and how I can access them?
I am also getting this error. 
```This annotation project has no assigned papers for your email address. You can make annotations but they won't be saved.```

Is there a way to get rid of all user verifications and just save annotations?
Please help me

**Comment by naourass** [comment]
Hi, you have to follow the CLI documentation here :
https://github.com/allenai/pawls/tree/main/cli

For local dev the email would be development_user@example.com
